GET http://localhost:8000/etas/project/all 
Content-Type: application/x-www-form-urlencoded
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNTIyOTE3NDc4LCJlbWFpbCI6ImJvbmdib25nY29AZ21haWwuY29tIn0.o37LrVEGOCi6sqydaZuJRT4S-VxhjDB6Ss4_0mSqRKw

###

GET http://localhost:8000/etas/issue/all 
Content-Type: application/x-www-form-urlencoded
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNTIyOTE3NDc4LCJlbWFpbCI6ImJvbmdib25nY29AZ21haWwuY29tIn0.o37LrVEGOCi6sqydaZuJRT4S-VxhjDB6Ss4_0mSqRKw

###

GET http://localhost:8000/etas/project/this_year
Content-Type: application/x-www-form-urlencoded
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNTIyOTE3NDc4LCJlbWFpbCI6ImJvbmdib25nY29AZ21haWwuY29tIn0.o37LrVEGOCi6sqydaZuJRT4S-VxhjDB6Ss4_0mSqRKw

###

GET http://localhost:8000/etas/vulnerability/closed/this_year
Content-Type: application/x-www-form-urlencoded
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNTIyOTE3NDc4LCJlbWFpbCI6ImJvbmdib25nY29AZ21haWwuY29tIn0.o37LrVEGOCi6sqydaZuJRT4S-VxhjDB6Ss4_0mSqRKw

###

GET http://localhost:8000/etas/summary/all
Content-Type: application/x-www-form-urlencoded
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNTIyOTE3NDc4LCJlbWFpbCI6ImJvbmdib25nY29AZ21haWwuY29tIn0.o37LrVEGOCi6sqydaZuJRT4S-VxhjDB6Ss4_0mSqRKw

###

GET http://localhost:8000/etas/business/all
Content-Type: application/x-www-form-urlencoded
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwiZXhwIjoxNTIyOTE3NDc4LCJlbWFpbCI6ImJvbmdib25nY29AZ21haWwuY29tIn0.o37LrVEGOCi6sqydaZuJRT4S-VxhjDB6Ss4_0mSqRKw