# Generated by Django 2.0.3 on 2018-04-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0007_remove_vulnerability_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='classification',
            field=models.CharField(choices=[('Request', 'Request'), ('Event', 'Event'), ('N/A', 'N/A')], max_length=80, verbose_name='진행 배경'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Fixed', 'Fixed'), ('Holding', 'Holding')], max_length=80, null=True, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Fixed', 'Fixed'), ('Holding', 'Holding')], max_length=80, null=True, verbose_name='상태'),
        ),
    ]
