# Generated by Django 2.0.3 on 2018-04-04 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0008_auto_20180404_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='project_code',
        ),
        migrations.AddField(
            model_name='comment',
            name='project_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='etas.Project'),
        ),
        migrations.AddField(
            model_name='report',
            name='caption',
            field=models.CharField(max_length=140, null=True, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='solution',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='project_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerabilitys', to='etas.Project'),
        ),
    ]
