# Generated by Django 2.0.3 on 2018-04-04 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0009_auto_20180404_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sequence',
            field=models.CharField(max_length=80, null=True, verbose_name='순서'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='project_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='etas.Project'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project_vuln_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='etas.Vulnerability'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='project_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilitys', to='etas.Project'),
        ),
    ]
