# Generated by Django 2.0.3 on 2018-04-04 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0010_auto_20180404_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='project_vuln_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='etas.Vulnerability'),
        ),
    ]
