# Generated by Django 2.0.3 on 2018-04-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0012_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='project_code',
            field=models.ManyToManyField(null=True, related_name='summarys', to='etas.Project'),
        ),
    ]
