# Generated by Django 2.0.3 on 2018-04-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0014_remove_summary_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closed_at',
            field=models.DateTimeField(null=True, verbose_name='개선 완료일'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='closed_at',
            field=models.DateTimeField(null=True, verbose_name='개선 완료일'),
        ),
    ]
