# Generated by Django 2.0.3 on 2018-04-09 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0015_auto_20180409_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='etas.Summary'),
        ),
        migrations.AddField(
            model_name='summary',
            name='business_code',
            field=models.CharField(max_length=80, null=True, verbose_name='사업 명'),
        ),
    ]
