# Generated by Django 2.0.3 on 2018-04-09 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0016_auto_20180409_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_code', models.CharField(max_length=80, null=True, verbose_name='사업 명')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='summary',
            name='business_code',
        ),
        migrations.AlterField(
            model_name='project',
            name='business_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='etas.Business'),
        ),
    ]
