# Generated by Django 2.0.3 on 2018-04-09 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0021_auto_20180409_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, null=True, verbose_name='이름')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='business',
            name='workers',
        ),
        migrations.AlterField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='project_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='etas.Project', verbose_name='프로젝트 코드'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='checker',
        ),
        migrations.AlterField(
            model_name='report',
            name='project_vuln_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='etas.Vulnerability', verbose_name='취약점 코드'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='business_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='etas.Business', verbose_name='사업 명'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='project_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilitys', to='etas.Project', verbose_name='프로젝트 명'),
        ),
        migrations.AddField(
            model_name='business',
            name='workers',
            field=models.ManyToManyField(to='etas.Worker', verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='project',
            name='checker',
            field=models.ManyToManyField(to='etas.Worker', verbose_name='검수자'),
        ),
    ]
