# Generated by Django 2.0.3 on 2018-04-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0023_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(max_length=80, null=True, verbose_name='역할'),
        ),
    ]
