# Generated by Django 2.0.3 on 2018-04-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0026_auto_20180409_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='opened_at',
            field=models.DateField(blank=True, null=True, verbose_name='프로젝트 등록일'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='opened_at',
            field=models.DateField(blank=True, null=True, verbose_name='취약점 등록일'),
        ),
    ]
