# Generated by Django 2.0.3 on 2018-04-09 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0027_auto_20180409_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='business_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='etas.Business', verbose_name='사업 명'),
        ),
    ]
