# Generated by Django 2.0.3 on 2018-04-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0002_auto_20180403_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creator',
        ),
    ]
