# Generated by Django 2.0.3 on 2018-04-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0011_auto_20180404_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.TextField(null=True)),
                ('business_status', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
