# Generated by Django 2.0.3 on 2018-04-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0013_summary_project_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='project_code',
        ),
    ]
