# Generated by Django 2.0.3 on 2018-04-09 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0017_auto_20180409_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='worker',
            field=models.CharField(max_length=120, null=True, verbose_name='수행 인력'),
        ),
        migrations.AddField(
            model_name='summary',
            name='business_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='etas.Business'),
        ),
        migrations.AlterField(
            model_name='project',
            name='checker',
            field=models.CharField(max_length=80, verbose_name='검수자'),
        ),
    ]
