# Generated by Django 2.0.3 on 2018-04-09 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0018_auto_20180409_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='worker',
            new_name='workers',
        ),
    ]
