# Generated by Django 2.0.3 on 2018-04-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0020_auto_20180409_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='closed_at',
            field=models.DateField(blank=True, null=True, verbose_name='개선 완료일'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='closed_at',
            field=models.DateField(blank=True, null=True, verbose_name='개선 완료일'),
        ),
    ]
