# Generated by Django 2.0.3 on 2018-04-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etas', '0025_auto_20180409_1222'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Summary',
            new_name='Issue',
        ),
        migrations.AlterField(
            model_name='worker',
            name='comment',
            field=models.CharField(max_length=80, null=True, verbose_name='담당 업무'),
        ),
    ]
